version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 1 15 * *" # 1am on 15th of each month
    cooldown:
      default-days: 14
    labels:
      - "type: Maintenance"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 1 15 * *" # 1am on 15th of each month
    cooldown:
      default-days: 14
    labels:
      - "type: Maintenance"
    groups:
      actions:
        patterns:
          - "*"
