# Install pre-commit hooks via
# pre-commit install

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 5c9b20b95f2bc1c4d3d929b83a96d5c96a29e752 # frozen: v3.9.8
    hooks:
      - id: prettier
        files: \.(html|md|yml|yaml|toml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2eeb5678de71a00c0902cbda7105d328432f72cb # frozen: v0.16.8
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: "57b21406f092110c18776e39b0bda50d37c945c8" # frozen: v2.4.3
    hooks:
      - id: codespell
