name: coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel setuptools spin
          python -m pip install ".[test]"
          python -m pip install --upgrade numpy
          python -m pip uninstall --yes scipy
          pip list

      - name: Measure test coverage
        run: |
          spin test -c -- --durations=10
          # Tests fail if using `--doctest-modules`. I.e.,
          # spin test -- --doctest-modules

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
