name: coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  report:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install ".[test]"
          pip list

      - name: Measure test coverage
        run: |
          python -m pytest --cov=lazy_loader --durations=10
          # Tests fail if using `--doctest-modules`. I.e.,
          # python -m pytest --cov=lazy_loader --doctest-modules --durations=20
          codecov
